#--------------------------------------------------------------------------------------------
# AES 키
#--------------------------------------------------------------------------------------------
aes.key=ThisIsASecretKey
aes.iv=FixedIVForAES128
